name: Tufuwu/test2
on:
  push:
    branches:
    - "**/*"
  pull_request:
#   # This item has no matching transformer
#   maximum_number_of_builds: 0
env:
  MAKEFLAGS: "-j2"
  PYTHON3: "/usr/bin/python3"
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: Set up cache
      uses: actions/cache@v3.3.2
      with:
        path: cache
        key: "${{ runner.os }}-path"
#     # 'sudo' was not transformed because there is no suitable equivalent in GitHub Actions
    - run: sudo apt-get update -qq
    - run: sudo apt-get install -qq -y --no-install-recommends python3-cairo python3-pil python3-htmlmin p7zip
    - run: "$PYTHON3 --version"
    - run: make
    - run: 7zr a dictionaries-"${{ github.ref }}".7z jmdict.mobi jmnedict.mobi combined.mobi
    - uses: softprops/action-gh-release@v0.1.15
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        GITHUB_REPOSITORY: "${{ github.repository }}"
      with:
        files: dictionaries-*.7z
      if: "${{ github.event_name == 'push' && ${{ github.ref }} }}"